# Generated by Django 5.2.4 on 2025-07-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('candidate', 'activity')},
        ),
    ]
