# Generated by Django 5.2.4 on 2025-08-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_globalsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procedurestation',
            unique_together={('name', 'level', 'session')},
        ),
    ]
