# Generated by Django 5.2.4 on 2025-07-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_score_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
