# Generated by Django 5.2.4 on 2025-08-08 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_candidate_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='procedurestation',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'All Levels'), (100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level'), (600, '600 Level')], null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
